threshold: 100
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - DrLight::ScientificNumber#value
      - DrLight::ScientificNumber#deviance
      - DrLight::ScientificNumber#initialize
      - DrLight::ScientificNumber::Formatter#initialize
      - DrLight::ScientificNumber::Normalizer#initialize
  ReturnTag:
    enabled: true
    exclude: []
  Summary::Presence:
    enabled: true
    exclude:
      - DrLight::ScientificNumber#initialize
      - DrLight::ScientificNumber::Formatter#initialize
      - DrLight::ScientificNumber::Normalizer#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
